### ISSUE TITLE
exception thrown in closest pair 

### ISSUE THREAD

**Issue by tbhaxor** [OpenGenus/cosmos#3447]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [x] Error
- [ ] Proposal to the Repository

**Details:**

File
```
cosmos/code/divide_conquer/src/closest_pair_of_points/closest_pair.py
```

Error (after formatting python file):
```
Traceback (most recent call last):
  File "closest_pair.py", line 48, in <module>
    print(closestpair([(0,0),(7,6),(2,20),(12,5),(16,16),(5,8),(19,7),(14,22),(8,19),(7,29),(10,11),(1,13)]))
  File "closest_pair.py", line 14, in closestpair
    d = sqdist(p,q)
  File "closest_pair.py", line 10, in sqdist
    def sqdist(p,q): return square(p[0]-q[0])+square(p[1]-q[1])
TypeError: 'int' object is not subscriptable
```

**Comment by mansiag** [comment]
I would like to work on this issue unless you are doing so already.

**Comment by arnavb** [comment]
@tbhaxor Please close this issue!
