### ISSUE TITLE
Exception thrown in rope.py

### ISSUE THREAD

**Issue by mansiag** [OpenGenus/cosmos#3456]
**This is a(n):**

- [ ] New algorithm
- [ ] Update to an existing algorithm
- [x] Error
- [ ] Proposal to the Repository

**Details:**

File

``` cosmos/blob/master/code/data_structures/src/tree/binary_tree/rope/rope.py```

Error

```Traceback (most recent call last):
File "rope.py", line 53, in <module>
class Rope:
File "rope.py", line 60, in Rope
def Index(self, ind, node=self.head):
NameError: name 'self' is not defined```

**Comment by erobynreid** [comment]
I would like to work on this if no one is doing so already.

**Comment by mansiag** [comment]
Yeah , go for it.:smile:

**Comment by ulshell** [comment]
I would like to correct it
